version: "3.9"
services:
  po_task.api:
    image: ${DOCKER_REGISTRY-}potaskapi
    build:
      context: .
      dockerfile: PO_Task.Api/Dockerfile
    ports:
      - "7188:7188"
    environment:
      - ASPNETCORE_URLS=http://+:7188
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=po-db;Database=PO_TaskDB;User Id=sa;Password=admin@123;TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq-demo
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - po-db
    networks:
      - po_demo_appnetwork

  po-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: po-db
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "admin@123"
      ACCEPT_EULA: "Y"
    networks:
      - po_demo_appnetwork
    volumes:
      - posqlserverdata:/var/opt/mssql

networks:
  po_demo_appnetwork:

volumes:
  posqlserverdata:
